### ISSUE TITLE
recommendations for oos_util_apex

### ISSUE THREAD

**Issue by Dani3lSun** [OraOpenSource/oos-utils#38]
Hi @martindsouza 
I`d created some gists maybe some interesting stuff for the oos_util_apex package...

1) Get BLOB / Filename / Mime_Type from apex_application_temp_files
https://gist.github.com/Dani3lSun/461a6d6f6eb991107802

2) Wrapper for APEX_ZIP.ADD_FILE for CLOB content
https://gist.github.com/Dani3lSun/46e2e75768cfae7175d6

3) check if an APEX item is rendered or not (I think Patrick Wolf posted about it some time ago)
https://gist.github.com/Dani3lSun/f5e620e748fb09e1f352

4) percentage usage of disk space of an Oracle XE 11g database
https://gist.github.com/Dani3lSun/c2e0f8bb249ec2ae7bd2

**Comment by martindsouza** [comment]
1: Can we not use `oos_util_apex.join_session` or `oos_util_apex.create_session` for this and then select from `apex_application_temp_files`

2: I don't think we need this function as the following will handle it:

```plsql
apex_zip.add_file(
  p_zipped_blob,
  p_name,
  oos_util_lob.clob2blob(p_clob_content));
```

3: Yes I'll add it. Do you have an example as to when you'd use this (I would like to include in documentation)

4: I like the idea but will not add to core packages since most users don't have access to `dba_free_space`. What do you think about creating an option `oos_util_dba` package that can be manually installed?

**Comment by Dani3lSun** [comment]
1) of course we can, haven´t referenced it, just copied my code to the gists...
2) Yep you´re right, haven´t seen the clob2blob function, cool!
3) I use it if I have to do custom page level validations (and a item gets not rendered because of an condition or authorization). If using item level validation APEX itself does this check, but on page level a not null validation would fire, because APEX thinks the item is there...
4) You´re right, haven´t thought about it (have most time SYS rights!:)) but a oos_util_dba package would be nice for all DBAs and of course developers who have more rights...

**Comment by martindsouza** [comment]
I have moved the two final suggestions to their own tickets:

3: #39 
4: #40
