### ISSUE TITLE
Package files are missing sqplus show error command

### ISSUE THREAD

**Issue by janihur** [OraOpenSource/oos-utils#65]
Is this by design or by accident ? The installation is anyway done with `sqlplus` and it would be nice also during development not to need to type `show errors` all the time.

I don't think adding `show errors` makes any damage, but that's not my call.

```plsql
create or replace package foo is
  null;
end;
/
show errors
```

**Comment by martindsouza** [comment]
@janihur the show errors isn't included since we compile all the packages in random (actually alphabetical) order. There are some cross dependancies and it's only after they're all compiled do we recompile all invalid objects. 

If we `show errors` then we'll probably get some false positives as the package did initially compile with an error. At the end of the install it should be fine.

This brings up a good idea though. What about doing a quick test against all `oos_util` objects from `user_objects` to ensure that they're compiled correctly. Are you ok with that?

**Comment by janihur** [comment]
I a-kind-of see the point of random compilation order. However in this context the dependencies should be minimal and one-way only - or is that just a naive idea.

You refer to some cross-dependencies - do you mean that package A depends on package B and package B depends on package A (a cyclic dependency) ?

I haven't checked the code from dependency point of view, but obviously I should, so I will.

**Comment by martindsouza** [comment]
@janihur I could be one way dependencies or cynical. I don't know as the packages are evolving. The current technique allows us to not be concerned about it and to be consistently recompiled and rebuilt.
