### ISSUE TITLE
Deterministic Clause

### ISSUE THREAD

**Issue by jzaldokas** [OraOpenSource/oos-utils#93]
What is the reason why deterministic clause is not used for many deterministic functions? I think there are many cases when calls to the utility functions would benefit from this clause. Are there any cases when this could be undesirable (for example, when calling oos_util_validation.is_number)?

**Comment by janihur** [comment]
The deterministic clause has some limitations. First it is in effect only in SQL context and second our functions so far are a quite simple so I don't see a huge potential gain. To overcome the first limitation we could use [function result cache](http://docs.oracle.com/cd/E11882_01/appdev.112/e25519/subprograms.htm#LNPLS00817) but unfortunately it's available only since 11g.

However I don't think adding deterministic makes any harm.

Could you (@jzaldokas) run performance tests to show the effect of the clause and then make a pull request ?

**Comment by martindsouza** [comment]
I've added this to some of the functions that I think are safe to do so.
