### ISSUE TITLE
oos_util_validation.is_email

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/oos-utils#97]
Would the function `oos_util_validation.is_email` fall under the scope of this project?

```sql
function is_email(p_str in varchar2)
    return boolean;
```

**Comment by janihur** [comment]
What are the rules used to define if `p_str` is an email or not ? `varchar2`size is also very limited - I'd prefer `clob` instead.

**Comment by zhudock** [comment]
The guide [here ](http://www.regular-expressions.info/email.html) seems to go into quite a bit of detail on designing a RegEx to validate an email address

**Comment by janihur** [comment]
@zhudock oh this is about email addresses ? My solution is [this](http://stackoverflow.com/a/36930558/272735) and preferred function signature:

```
function is_email_address(p_str in varchar2) return boolean;
```

**Comment by martindsouza** [comment]
I appreciate the interest in this issue. Email validation has always been a difficult thing to nail down. There's been a few good links and they all end up saying the same thing: It's nearly impossible to validate an email address via regular express. [This article](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/) highlights the case.

Because each organization may have different rules I'm going to close this ticket for now. If we find in the future that we can come up with a better way of doing it then we can re-open.
